version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "LATEST"
        LoadBalancerInfo:
          ContainerName: finaltestapp
          ContainerPort: 5000
