version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 345594581177.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t finaltestapp ./src
      - docker tag finaltestapp:latest 345594581177.dkr.ecr.us-east-1.amazonaws.com/finaltestapp:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 345594581177.dkr.ecr.us-east-1.amazonaws.com/finaltestapp:latest
artifacts:
  files: '**/*'
